spring.application.name=mottu-challenge

spring.datasource.url=jdbc:sqlserver://mottu-server.database.windows.net:1433;database=mottu-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=admin557605@mottu-server
spring.datasource.password=260705Nd*
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace

server.port=8080