CREATE TABLE t_mtu_user(
    id_user bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nr_email VARCHAR(255) NOT NULL,
    pw_senha VARCHAR(255) NOT NULL,
    vl_role VARCHAR(10) CHECK (vl_role IN ('ADMIN', 'USER'))
);